function generatePhoto() {
    const photos = [
    "images/photo1.jpeg",
    "images/photo2.jpeg",
    "images/photo3.jpeg",
    "images/photo4.jpeg",
    "images/photo5.jpeg",
    "images/photo6.jpeg",
    "images/photo7.jpeg",
    "images/photo8.jpeg",
    "images/photo9.jpeg",
    "images/photo10.jpeg",
    "images/photo11.jpeg",
    "images/photo12.jpeg",
    "images/photo13.jpeg",
    "images/photo14.jpeg",
    "images/photo15.jpeg",
    "images/photo16.jpeg",
    "images/photo17.jpeg",
    "images/photo18.jpeg",
    "images/photo19.jpeg",
    "images/photo20.jpeg",
    "images/photo21.jpeg",
    "images/photo22.jpeg",
    "images/photo23.jpeg",
    "images/photo24.jpeg",
    "images/photo25.jpeg",
    "images/photo26.jpeg",
    "images/photo27.jpeg",
    "images/photo28.jpeg",
    "images/photo29.jpeg",
    "images/photo30.jpeg",
    "images/photo31.jpeg",
    "images/photo32.jpeg",
    "images/photo33.jpeg",
    "images/photo34.jpeg",
    "images/photo35.jpeg",
    "images/photo36.jpeg",
    "images/photo37.jpeg",
    "images/photo38.jpeg",
    "images/photo39.jpeg",
    "images/photo40.jpeg",
    "images/photo41.jpeg",
    "images/photo42.jpeg",
    "images/photo43.jpeg",
    "images/photo44.jpeg",
    "images/photo45.jpeg",
    "images/photo46.jpeg",
    "images/photo47.jpeg",
    "images/photo48.jpeg",
    "images/photo49.jpeg",
    "images/photo50.jpeg",
    "images/photo51.jpeg",
    "images/photo52.jpeg",
    "images/photo53.jpeg",
    "images/photo54.jpeg",
    "images/photo55.jpeg",
    "images/photo56.jpeg",
    "images/photo57.jpeg",
    "images/photo58.jpeg",
    "images/photo59.jpeg",
    "images/photo60.jpeg"
    ];
    const img = document.getElementById("photoDisplay");
    const randomIndex = Math.floor(Math.random() * photos.length);
    document.getElementById("photoDisplay").src = photos[randomIndex];

    img.src = photos[randomIndex];
    img.style.display = "block";
}
